# docker-compose.yml

name: fragments-app
services:
    # Fragments microservice API server
    fragments:
        # use a proper init process ( tini)
        init: true
        # Build the docker img using the Dockerfile
        # and current directory as the build context
        build:
            context: ./fragments
            dockerfile: Dockerfile
        # Environment variables
        environment:
            - API_URL=http://localhost:8080
            - HTPASSWD_FILE=tests/.htpasswd
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - NODE_ENV=development
            - AWS_REGION=us-east-1
            # LocalStack AWS credentials (required for S3 access)
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - AWS_SESSION_TOKEN=test
            - AWS_DEFAULT_REGION=us-east-1
            # Use the LocalStack endpoint vs. AWS for S3 AWS SDK clients.
            # NOTE: we use Docker's internal network to the localstack container
            - AWS_S3_ENDPOINT_URL=http://localstack:4566
            # Use the DynamoDB local endpoint vs. AWS for DynamoDB AWS SDK clients.
            - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
            # This S3 bucket and DynamoDB table need to get created first, see
            # local-aws-setup.sh. We'll default to 'fragments' as the name, unless
            # something else is defined in the env.
            - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-fragments}
            - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
        # Port to publish
        ports:
            - "8080:8080"

    # DynamoDB local ( mock DynamoDB service)
    dynamodb-local:
        image: amazon/dynamodb-local
        ports:
            # default port is 8000
            - "8000:8000"
        # command to run DynamoDB in memory
        command: ["-jar", "DynamoDBLocal.jar", "-inMemory"]

    # LocalStack for S3 (mock S3 service)
    localstack:
        image: localstack/localstack:3
        ports:
            - "4566:4566"
        environment:
            # run only S3 service
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
