name: fragmentUI-CI/CD

on:
    pull_request:
        branches:
            - main
        paths:
            - "assignments/fragments-ui/**"
    push:
        branches:
            - main
        paths:
            - "assignments/fragments-ui/**"

jobs:
    ci:
        name: CI - Test & Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set-up node
              uses: actions/setup-node@v4
              with:
                  node-version: "24"

            - name: Install dependencies
              working-directory: assignments/fragments-ui
              run: npm ci

            - name: Build project
              working-directory: assignments/fragments-ui
              run: npm run build

    deploy-to-s3:
        name: CD - Deploy to S3 + CloudFront
        needs: ci
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set-up node
              uses: actions/setup-node@v4
              with:
                  node-version: "24"

            - name: Install dependencies
              working-directory: assignments/fragments-ui
              run: npm ci

            - name: Build project
              working-directory: assignments/fragments-ui
              run: npm run build

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Deploy to S3
              run: |
                  aws s3 sync assignments/fragments-ui/dist s3://cdcuray-fragments-ui \
                    --delete \
                    --region us-east-1

            - name: Invalidate CloudFront cache
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"
